development:
  adapter: postgresql
  encoding: unicode
  database: meatup_development
  pool: 5
  username: sashafklein
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meatup_test
  pool: 5
  username: sashafklein
  password: